import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './Provider'
import { SideBar } from '@/components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex">
        <Provider>
          <SideBar />
          <div className="w-full">{children}</div>
        </Provider>
      </body>
    </html>
  )
}
